boat: 
  path: 'rhdiffusion.boat.base_diffusion_boat'
  name: 'BaseDiffusionBoat'            

  models:
    net: $net

    upsample: $upsample

    scheduler:
      path: 'rhdiffusion.schedulers.scheduling_ddim'
      name: 'DDIMScheduler'
      config:
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: "linear"
        steps_offset: 1
        clip_sample: false
        set_alpha_to_one: false
        prediction_type: "epsilon"
        num_train_timesteps: 1000

    solver:
      path: 'rhdiffusion.solvers.sampling_ddim'
      name: 'DDIMSampler'
      config:
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: "linear"
        steps_offset: 1
        clip_sample: false
        set_alpha_to_one: false
        prediction_type: "epsilon"
        num_train_timesteps: 1000
        eta: 0.0
        num_inference_steps: 50
  
  losses: 
    net:
      path: 'rhopsr.nn.losses.weighted_loss'
      name: 'WeightedLoss'
      params:
        base_loss_fn_str: mse
      wrapper: # This wrapper is more complex needs parameters
        mpath: 'rhopsr.nn.losses.wrappers.list_of_keys.ListOfKeys'
        params:
          keys: ["preds", "targets", "weights"]
          
optimization: 
  net:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      weight_decay: 0.0
    lr_scheduler: {}

  use_ema:
    ema_decay: 0.999
    ema_start: $ema_start

trainer: 
  devices: $devices
  max_epochs: $max_epochs
  val_check_epochs: 1
  state_save_epochs: 1
  save_images: true

validation: 
  save_images: true
  num_vis_samples: 4
  target_metric_name: 'psnr'
  metrics:
    psnr:
      path: 'torchmetrics.image'
      name: 'PeakSignalNoiseRatio'
      wrapper: 'rhcore.metrics.wrappers.dict_2_params.Dict2ListParams'
      params:
        data_range: 2.0
    ssim:
      path: 'torchmetrics.image'
      name: 'StructuralSimilarityIndexMeasure'
      wrapper: 'rhcore.metrics.wrappers.dict_2_params.Dict2ListParams'
      params: {}

data: 
  path: rhcore.data.data_modules.ddp_data_module
  name: DistTrainDistValidDataModule
  config: 
    train_dataloader: 
      dataset:
        path: 'rhcore.data.datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params: 
          folder_paths: $train_folder_paths
          extensions:
           gt: [png, jpg]
           cond: [png, jpg]
          data_prefix:
            gt: ''
            lq: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, lq]
            - type: Normalize
              keys: [gt, lq]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $train_batch_size
      num_workers: $num_workers
      pin_memory: false
      persistent_workers: false
      sampler:
        type: DefaultSampler
        shuffle: true
    
    valid_dataloader: 
      dataset: 
        path: 'rhcore.data.datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params: 
          folder_paths: $valid_folder_paths
          data_prefix:
            gt: ''
            lq: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, lq]
            - type: Normalize
              keys: [gt, lq]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $valid_batch_size
      num_workers: $num_workers
      persistent_workers: true
      sampler:
        type: DefaultSampler
        shuffle: true

logging:
  root_dir: 'work_dirs'
  name: $experiment_name
  loggers:
    tensorboard:
      path: 'trainer.loggers.tensorboard'
      name: 'TensorBoardLogger'
      params:
        log_dir: 'work_dirs'
        name: $experiment_name

callbacks: 
  - path: trainer.callbacks.state_cleaner
    name: KeepTopKStateCallback
    params:
      top_k: 5